"""my_any_ctrl – набор пользовательских wxPython-виджетов."""

from .widgets import (
    Buble_size_Pref,
    MyStaticBox,
    MOG_Pref,
    PopUPField,
    MySliderCtrl,
    MyKnobSpinCtrl,
    MyRadioButton,
    MyButton,
    MyDisplay,
    MyGauge2,
    MyGauge,
    MySpinCtrl,
    PopUPKeyboard,
    TouchSpinCtrl,
    TouchBtn,
    TouchPanel,
    XDAV,
)

__all__ = [
    "Buble_size_Pref",
    "MyStaticBox",
    "MOG_Pref",
    "PopUPField",
    "MySliderCtrl",
    "MyKnobSpinCtrl",
    "MyRadioButton",
    "MyButton",
    "MyDisplay",
    "MyGauge2",
    "MyGauge",
    "MySpinCtrl",
    "PopUPKeyboard",
    "TouchSpinCtrl",
    "TouchBtn",
    "TouchPanel",
    "XDAV",
]
